apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wxaa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wxaa
    app.kubernetes.io/part-of: ci10t-786-0078-app
  name: devfile-sample-wxaa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wxaa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wxaa
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0078-tenant/ci10t-786-0078-app/devfile-sample-wxaa@sha256:944d1630054e1e23d7c4b3dd96de6f04564ff44c373827dfc803b65d96205aa3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
